# Common Labels
labels:
  app: "individual"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "individual"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "individual_schema"
    image:
      repository: "individual-db"

# Container Configs
image:
  repository: "individual"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/individual/health"
  readinessProbePath: "/individual/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx384m -Xms384m"
memory_limits: 512Mi
java-args: ""
persist-yml-path: "file:///work-dir/health-campaign-config/egov-persister/individual-persister.yml"
indexer-yml-path: "file:///work-dir/health-campaign-config/egov-persister/individual-indexer.yml"
egov-idgen-host-key: "egov-idgen"
egov-beneficiary-idgen-host-key: "beneficiary-idgen"
egov-idgen-generate-path: "egov-idgen/id/_generate"
egov-beneficiary-idgen-idpool-search-path: "beneficiary-idgen/id/id_pool/_search"
egov-beneficiary-idgen-idpool-update-path: "beneficiary-idgen/id/id_pool/_update"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: health-individual
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ index .Values "egov-idgen-host-key" | quote }}
  - name: EGOV_BENEFICIARY_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ index .Values "egov-beneficiary-idgen-host-key" | quote }}
  - name: EGOV_IDGEN_PATH
    value: {{ index .Values "egov-idgen-generate-path" | quote }}
  - name: EGOV_BENEFICIARY_IDGEN_IDPOOL_SEARCH_PATH
    value: {{ index .Values "egov-beneficiary-idgen-idpool-search-path" | quote }}
  - name: EGOV_BENEFICIARY_IDGEN_IDPOOL_UPDATE_PATH
    value: {{ index .Values "egov-beneficiary-idgen-idpool-update-path" | quote }}
  - name: EGOV_IDGEN_INTEGRATION_ENABLED
    value: "true"
  - name: EGOV_BENEFICIARY_IDGEN_INTEGRATION_ENABLED
    value: "true"
  - name: INDIVIDUAL_BENEFICIARY_ID_VALIDATION_ENABLED
    value: "true"
  - name: IDGEN.INDIVIDUAL.ID.FORMAT
    value: "individual.id"
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
  - name: SPRING_CACHE_AUTOEXPIRY
    value: "true"
  - name: INDIVIDUAL.CONSUMER.BULK.CREATE.TOPIC
    value: "individual-consumer-bulk-create-topic"
  - name: INDIVIDUAL.CONSUMER.BULK.UPDATE.TOPIC
    value: "individual-consumer-bulk-update-topic"
  - name: INDIVIDUAL.CONSUMER.BULK.DELETE.TOPIC
    value: "individual-consumer-bulk-delete-topic"
  - name: INDIVIDUAL.PRODUCER.SAVE.TOPIC
    value: "save-individual-topic"
  - name: INDIVIDUAL.PRODUCER.UPDATE.TOPIC
    value: "update-individual-topic"
  - name: INDIVIDUAL.PRODUCER.DELETE.TOPIC
    value: "delete-individual-topic"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  - name: EGOV_STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/mdms-v2/v1/_search"
  - name: EGOV_MDMS_PATH
    value: "/mdms-v2/v1/_search"
  - name: MDMS_PATH
    value: "/mdms-v2/v1/_search"
  - name: EGOV_ENC_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  - name: EGOV_ENC_ENCRYPT_ENDPOINT
    value: "/egov-enc-service/crypto/v1/_encrypt"
  - name: EGOV_ENC_DECRYPT_ENDPOINT
    value: "/egov-enc-service/crypto/v1/_decrypt"
  - name: EGOV_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: boundary-service
  - name: EGOV_BOUNDARY_SEARCH_URL
    value: "/boundary-service/boundary/_search"
  - name: EGOV_BOUNDARY_HIERARCHY_NAME
    value: "ADMIN"
  - name: AADHAAR_PATTERN
    value: "\\d{12}"
  - name: MOBILE_PATTERN
    value: "\\d+"
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_CREATE_USER_URL
    value: "/user/users/_createnovalidate"
  - name: EGOV_SEARCH_USER_URL
    value: "/user/_search"
  - name: EGOV_UPDATE_USER_URL
    value: "/user/users/_updatenovalidate"
  - name: EGOV_USER_INTEGRATION_ENABLED
    value: "true"
  - name: USER_SYNC_ENABLED
    value: "true"
  - name: USER_SERVICE_USER_TYPE
    value: "CITIZEN"
  - name: USER_SERVICE_ACCOUNT_LOCKED
    value: "false"
  - name: INDIVIDUAL_PRODUCER_UPDATE_USER_ID_TOPIC
    value: "update-user-id-topic"
  - name: NOTIFICATION_SMS_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}